ROUTE = [
    ("turn_180",),
    ("record_start",),
    ("walk",18),
    ("record_stop",),
    ("record_start",),
    ("climb",10),
    ("record_stop",),
    ("record_start",),
    ("walk",10),
    ("record_stop",),
    ("turn_right_90",),
    ("record_start",),
    ("walk",10),
    ("record_stop",),
    ("teleport",)
]
PORTAL=[1500,650]
NEXT_PORTAL=[1130,835]
